# Generated by Django 2.1.5 on 2019-01-31 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Type', models.CharField(choices=[('CS', 'Customer'), ('SL', 'Seller'), ('AD', 'Admin')], max_length=2)),
                ('ID', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Birthdate', models.DateField(default=django.utils.timezone.now)),
                ('Contact_No', models.IntegerField(blank=True, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Added_On', models.DateTimeField(auto_now_add=True)),
                ('Last_Access', models.DateTimeField(auto_now=True)),
                ('BillingAddress', models.CharField(max_length=100)),
                ('ShippingAddress', models.CharField(max_length=100)),
                ('Logo', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
