# Generated by Django 2.1.5 on 2019-01-31 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Price', models.IntegerField(default=100)),
                ('Product_Image', models.CharField(default='unknown', max_length=30)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Brand', to='Product.Brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='Product.Category')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_Product', to='Profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCatName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='Sub_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Category', to='Product.SubCategory'),
        ),
    ]
