# Generated by Django 2.1.5 on 2019-04-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_quntity', models.PositiveIntegerField(default=1)),
                ('Order_type', models.CharField(choices=[('SC', 'Success'), ('PN', 'Pending'), ('RJ', 'Rejected'), ('IC', 'IN Cart'), ('PR', 'Processed')], max_length=5)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prod_Details', to='Product.Item')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='Profiles.Profile')),
            ],
        ),
    ]
